######################################
# --- myMagicPearl v2.0.0 Plugin --- #
######################################

#This is a config for myMagicPearl plugin!
#More info you can find in plugin documentation or in our discord: https://discord.gg/qTpgQXQZye

#Plugin checking for new updates
check-for-updates: true

#Plugin automatically download and install a new version of plugin
auto-update: true

#Pearl settings
pearl:
  slot: 0
  display-name: "&dMagic Pearl"
  default-cooldown: 10
  #If you want to create a custom pearl you can use "/mymagicpearl setpearl" to set pearl what you have in hand
  meta-data: []

#Pearl lobby settings
lobby:
  enabled: true
  use-yaw-and-pitch: true
  location:
    x: {}
    y: {}
    z: {}
    world: {}
    yaw: {}
    pitch: {}

#Actions like: drop, change slot, itp.
allow-inventory-action: false

#Pearl give damage on teleportation
pearl-give-damage: false

#Replace item on slot while giving pearl
replace-item: true

#Pearl subtitles
subtitles:
  enabled: true
  action-bar: "&eUsing pearl..."

#Particles
particles:
  enabled: false
  particle: VILLAGER_HAPPY
  intensity: 1

#Permissions
permissions: []