name: myMagicPearl
version: '${project.version}'
main: me.zombix.myMagicPearl.MyMagicPearl
api-version: '1.16'
authors: [ Zombix3000 ]
description: Fly through your lobby with the power of the Magic Pearl!
commands:
  mymagicpearl:
    description: myMagicPearl plugin command
    usage: /mymagicpearl <givepearl/setpearllobby/setpearl/permission/reload/update> <add/delete>
    aliases: [ mymp ]
  givepearl:
    description: Give pearl to player
    usage: /givepearl
  setpearllobby:
    description: Set pearl lobby
    usage: /setpearllobby

permissions:
  mymagicpearl.givepearl:
    description: Allow to use /givepearl command
    default: true
  mymagicpearl.throwpearl:
    description: Allow to throw pearls
    default: true
  mymagicpearl.teleporttolobby:
    description: Allow to teleport to pearl lobby
    default: true
  mymagicpearl.admin:
    description: Allow to use /mymagicpearl <givepearl/setpearllobby/setpearl/permission/reload/update> <add/delete>
    default: op