name: myMagicPearl
version: '1.0'
main: me.zombix.mymagicpearl.MyMagicPearl
api-version: '1.20'
commands:
  mymagicpearl:
    description: myMagicPearl plugin command
    usage: /mymagicpearl <givepearl/reload/update>
    aliases:
      - givepearl
      - reload
      - update
      - setpearllobby
  givepearl:
    description: Give pearl command
    usage: /givepearl
  setpearllobby:
    description: Set pearl lobby
    usage: /setpearllobby

permissions:
  mymagicpearl.mymagicpearl:
    description: Allow to use /mymagicpearl command
    default: true
  mymagicpearl.reload:
    description: Allow to use /mymagicpearl reload command
    default: op
  mymagicpearl.update:
    description: Allow to use /mymagicpearl update command
    default: op
  mymagicpearl.givepearl:
    description: Allow to use /givepearl command
    default: true
  mymagicpearl.setpearllobby:
    description: Allow to use /setpearllobby commad
    default: op
  mymagicpearl.throwpearl:
    description: Allow to throw pearls
    default: true
  mymagicpearl.teleporttolobby:
    description: Allow to teleport to pearl lobby
    default: true